hic:
    image: node:18.16.0
    before_script:
        - apt-get update
        - apt-get install -y lftp
        - apt-get install -y wget
    stage: deploy
    when: always
    tags:
        - hva
    cache:
        key:
            files:
                - package-lock.json
            prefix: npm
        paths:
            - node_modules/
    script:
        - npm install
        - npm run test
        - npm run build
        - echo "enviroment > $HIC_ENVIRONMENT, host > $HIC_SFTP_HOST, username > $HIC_SFTP_USERNAME, password > $HIC_SFTP_PASSWORD"
        - lftp -e "set sftp:auto-confirm yes;open --user $HIC_SFTP_USERNAME --pass $HIC_SFTP_PASSWORD $HIC_SFTP_HOST; mirror --reverse --verbose=3 --delete dist/web/ $HIC_ENVIRONMENT/wwwroot/; mirror --reverse --verbose=3 --delete dist/api/ $HIC_ENVIRONMENT/app/; bye"
        - 'wget --header="Authorization: $HIC_API_KEY" $HIC_API_URL/$HIC_ENVIRONMENT/Restart'
    artifacts:
        paths:
            - dist
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $DEPLOY_HIC == "true"
          variables:
              HIC_ENVIRONMENT: "live"
        - if: $CI_COMMIT_BRANCH == "dev" && $DEPLOY_HIC == "true"
          variables:
              HIC_ENVIRONMENT: "dev"
        - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH != "dev" && $DEPLOY_HIC == "true"
          when: manual
          variables:
              HIC_ENVIRONMENT: "dev"
